"""Focused, evidence-based challenge classification."""

from __future__ import annotations

import re
from dataclasses import dataclass

from .contracts import ChallengeResult


@dataclass(frozen=True, slots=True)
class _Rule:
    kind: str
    patterns: tuple[str, ...]
    retryable: bool = True
    human: bool = False
    terminal: bool = False


_RULES = (
    _Rule("turnstile", (r"cf-turnstile", r"challenges\.cloudflare\.com/turnstile"), human=True),
    _Rule("cloudflare", (r"cf-chl-", r"cloudflare ray id", r"checking your browser")),
    _Rule("akamai", (r"akamai (?:bot|ghost)", r"_abck")),
    _Rule("datadome", (r"datadome", r"geo\.captcha-delivery\.com"), human=True),
    _Rule("imperva", (r"incapsula", r"imperva", r"visid_incap")),
    _Rule("perimeterx", (r"perimeterx", r"px-captcha", r"_pxhd"), human=True),
    _Rule("wordfence", (r"wordfence", r"generated by wordfence")),
    _Rule("javascript_challenge", (r"enable javascript and cookies", r"javascript is required to continue")),
    _Rule("visual_captcha", (r"g-recaptcha", r"hcaptcha", r"captcha-container"), human=True),
    _Rule("otp", (r"one[- ]time passcode", r"verification code sent to"),
          retryable=False, human=True, terminal=True),
    _Rule("device_confirmation", (r"device confirmation", r"approve this sign[ -]in"),
          retryable=False, human=True, terminal=True),
    _Rule("account_verification", (r"verify your account", r"confirm your identity"),
          retryable=False, human=True, terminal=True),
    _Rule("regional_block", (r"not available in your (?:country|region)", r"unavailable for legal reasons"),
          retryable=False, terminal=True),
    _Rule("rate_limited", (r"too many requests", r"rate limit exceeded", r"temporarily rate limited")),
    _Rule("access_denied", (r"request (?:was )?blocked", r"you have been denied access")),
)


def classify_challenge(
        *,
        title: str = "",
        body_text: str = "",
        html: str = "",
        final_url: str | None = None,
        http_status: int | None = None,
        engine: str | None = None,
) -> ChallengeResult:
    # Challenge terms in article prose are weak evidence. A rule needs either a
    # machine marker/URL or corroboration from title/status plus visible text.
    title_lower = title.lower()
    sample = f"{title}\n{body_text[:20_000]}\n{html[:40_000]}\n{final_url or ''}".lower()
    status_signal = http_status in {403, 407, 409, 423, 429, 451, 503}
    challenge_title = any(term in title_lower for term in (
        "attention required", "just a moment", "access denied", "security check", "verify you are human",
    ))
    for rule in _RULES:
        indicators = [pattern for pattern in rule.patterns if re.search(pattern, sample, re.IGNORECASE)]
        if not indicators:
            continue
        machine_indicator = any(token in " ".join(indicators) for token in ("cf-", "captcha", "_abck", "incapsula", "_px"))
        if not (machine_indicator or status_signal or challenge_title or indicators[0].startswith("not available")):
            continue
        confidence = min(0.99, 0.62 + 0.12 * len(indicators) + (0.12 if status_signal else 0.0))
        return ChallengeResult(
            kind=rule.kind,
            confidence=confidence,
            indicators=indicators,
            http_status=http_status,
            final_url=final_url,
            engine=engine,
            retryable=rule.retryable,
            terminal=rule.terminal,
            human_action_required=rule.human,
            instructions=(
                "Complete the verification in the retained browser session, then resume with the same session_id."
                if rule.human else None
            ),
        )
    if status_signal:
        return ChallengeResult(
            kind="rate_limited" if http_status == 429 else "http_block",
            confidence=0.72,
            indicators=[f"http_status:{http_status}"],
            http_status=http_status,
            final_url=final_url,
            engine=engine,
            retryable=http_status not in {407, 451},
            terminal=http_status in {407, 451},
        )
    return ChallengeResult(final_url=final_url, http_status=http_status, engine=engine)

