"""Focused, evidence-based protection classification for the browser runtime."""

from __future__ import annotations

import re
import time
from email.utils import parsedate_to_datetime
from dataclasses import dataclass
from typing import Mapping

from .contracts import ChallengeResult


@dataclass(frozen=True, slots=True)
class _Rule:
    kind: str
    patterns: tuple[str, ...]
    retryable: bool = True
    human: bool = False
    terminal: bool = False


_RULES = (
    _Rule("turnstile", (r"cf-turnstile", r"challenges\.cloudflare\.com/turnstile"), human=True),
    _Rule("cloudflare", (r"cf-chl-", r"cloudflare ray id", r"checking your browser")),
    _Rule("akamai", (r"akamai (?:bot|ghost)", r"_abck")),
    _Rule("datadome", (r"datadome", r"geo\.captcha-delivery\.com"), human=True),
    _Rule("imperva", (r"incapsula", r"imperva", r"visid_incap")),
    _Rule("perimeterx", (r"perimeterx", r"px-captcha", r"_pxhd"), human=True),
    _Rule("kasada", (r"\bkasada\b", r"kpsdk", r"x-kpsdk", r"ips\.js")),
    _Rule("queue_it", (r"queue-it(?:\.net)?", r"queue(?:ing)? (?:system|room)"), human=True),
    _Rule("wordfence", (r"wordfence", r"generated by wordfence")),
    _Rule("javascript_challenge", (r"enable javascript and cookies", r"javascript is required to continue")),
    _Rule("visual_captcha", (r"g-recaptcha", r"hcaptcha", r"captcha-container"), human=True),
    _Rule("otp", (r"one[- ]time passcode", r"verification code sent to"),
          retryable=False, human=True, terminal=True),
    _Rule("device_confirmation", (r"device confirmation", r"approve this sign[ -]in"),
          retryable=False, human=True, terminal=True),
    _Rule("account_verification", (r"verify your account", r"confirm your identity"),
          retryable=False, human=True, terminal=True),
    _Rule("regional_block", (r"not available in your (?:country|region)", r"unavailable for legal reasons"),
          retryable=False, terminal=True),
    _Rule("auth_paywall", (r"(?:sign |log )?in to continue", r"subscription required", r"members only", r"paywall"),
          retryable=False, terminal=True),
    _Rule("rate_limited", (r"too many requests", r"rate limit exceeded", r"temporarily rate limited")),
    _Rule("access_denied", (r"request (?:was )?blocked", r"you have been denied access")),
)

_ARTICLE_SIGNALS = (
    "<article", "property=\"article:", "property='article:", "\"@type\":\"newsarticle\"",
    "\"@type\":\"article\"", "itemprop=\"articlebody\"", "class=\"entry-content",
    "class='entry-content", "class=\"article-body", "class='article-body", "class=\"post-content",
    "class='post-content", "class=\"story-body", "class='story-body", "property=\"og:type\" content=\"article\"",
)
_LINGERING_MARKERS = ("cloudflare", "akamai", "imperva", "incapsula", "datadome", "perimeterx", "slow down")
_HEADER_RULES = (
    ("cloudflare", ("cf-mitigated", "cf-ray", "server:cloudflare")),
    ("akamai", ("x-akamai", "server:akamaighost", "server:akamai")),
    ("imperva", ("x-iinfo", "incap_ses", "visid_incap", "server:imperva", "server:incapsula")),
    ("datadome", ("x-datadome", "datadome")),
    ("perimeterx", ("x-px-",)),
    ("kasada", ("x-kpsdk",)),
    ("aws_waf", ("x-amzn-waf-action",)),
)


def _article_signal_count(html: str) -> int:
    return sum(marker in html for marker in _ARTICLE_SIGNALS)


def _retry_after_seconds(headers: Mapping[str, str]) -> int | None:
    value = headers.get("retry-after", "").strip()
    if not value:
        return None
    try:
        return max(0, int(value))
    except ValueError:
        try:
            return max(0, int(parsedate_to_datetime(value).timestamp() - time.time()))
        except (TypeError, ValueError, OverflowError):
            return None


def _header_indicators(headers: Mapping[str, str]) -> tuple[str | None, list[str]]:
    flattened = "\n".join(f"{key}:{value}" for key, value in headers.items()).lower()
    for kind, markers in _HEADER_RULES:
        matched = [marker for marker in markers if marker in flattened]
        if matched:
            return kind, matched
    return None, []


def classify_challenge(
        *,
        title: str = "",
        body_text: str = "",
        html: str = "",
        final_url: str | None = None,
        http_status: int | None = None,
        engine: str | None = None,
        response_headers: Mapping[str, str] | None = None,
) -> ChallengeResult:
    # Challenge terms in article prose are weak evidence. A rule needs either a
    # machine marker/URL or corroboration from title/status plus visible text.
    title_lower = title.lower()
    headers = {str(key).lower(): str(value).lower() for key, value in (response_headers or {}).items()}
    sample = f"{title}\n{body_text[:20_000]}\n{html[:40_000]}\n{final_url or ''}".lower()
    status_signal = http_status in {403, 407, 409, 423, 429, 451, 503}
    article_signals = _article_signal_count(html.lower())
    recovered_article = len(html) > 8_000 and article_signals >= 1
    retry_after = _retry_after_seconds(headers)
    header_kind, header_matches = _header_indicators(headers)
    challenge_title = any(term in title_lower for term in (
        "attention required", "just a moment", "access denied", "security check", "verify you are human",
    ))
    if http_status == 429 or retry_after is not None:
        return ChallengeResult(
            kind="rate_limited", confidence=0.95 if http_status == 429 else 0.88,
            indicators=([f"http_status:{http_status}"] if http_status == 429 else [])
            + (["retry-after"] if retry_after is not None else []),
            http_status=http_status, final_url=final_url, engine=engine,
            # A bounded cooldown is safer than immediately retrying a publisher that explicitly throttled us.
            retryable=False, retry_after_seconds=retry_after,
        )
    if http_status == 404 and not recovered_article:
        # A confirmed missing document should not trigger the browser's
        # challenge/fallback loop. Some challenge flows expose an initial 404
        # before replacing the DOM, which the recovered-document guard avoids.
        return ChallengeResult(
            kind="missing_source",
            confidence=0.96,
            indicators=["http_status:404"],
            http_status=http_status,
            final_url=final_url,
            engine=engine,
            retryable=False,
            terminal=True,
        )
    if http_status == 401 or any(token in (final_url or "").lower() for token in ("/login", "/signin", "/auth/")):
        return ChallengeResult(
            kind="auth_paywall", confidence=0.95, indicators=[f"http_status:{http_status}"] if http_status == 401 else ["login_redirect"],
            http_status=http_status, final_url=final_url, engine=engine, retryable=False, terminal=True,
        )
    if header_kind and (status_signal or challenge_title or article_signals == 0):
        human = header_kind in {"datadome", "perimeterx"}
        return ChallengeResult(
            kind=header_kind, confidence=0.92 if status_signal else 0.78, indicators=header_matches,
            http_status=http_status, final_url=final_url, engine=engine, retryable=not human,
            human_action_required=human,
            instructions="Complete the verification in the retained browser session, then resume with the same session_id." if human else None,
        )
    for rule in _RULES:
        indicators = [pattern for pattern in rule.patterns if re.search(pattern, sample, re.IGNORECASE)]
        if not indicators:
            continue
        machine_indicator = any(token in " ".join(indicators) for token in ("cf-", "captcha", "_abck", "incapsula", "_px"))
        # Articles regularly mention WAF vendors and CAPTCHA. A 200 article with
        # only lingering vendor prose is not a protection page.
        if article_signals and not status_signal and not challenge_title and all(
                marker in _LINGERING_MARKERS for marker in indicators):
            continue
        if not (machine_indicator or status_signal or challenge_title or indicators[0].startswith("not available")):
            continue
        confidence = min(0.99, 0.62 + 0.12 * len(indicators) + (0.12 if status_signal else 0.0))
        return ChallengeResult(
            kind=rule.kind,
            confidence=confidence,
            indicators=indicators,
            http_status=http_status,
            final_url=final_url,
            engine=engine,
            retryable=rule.retryable,
            terminal=rule.terminal,
            human_action_required=rule.human,
            instructions=(
                "Complete the verification in the retained browser session, then resume with the same session_id."
                if rule.human else None
            ),
            retry_after_seconds=retry_after,
        )
    if status_signal:
        return ChallengeResult(
            kind="rate_limited" if http_status == 429 else "http_block",
            confidence=0.72,
            indicators=[f"http_status:{http_status}"],
            http_status=http_status,
            final_url=final_url,
            engine=engine,
            retryable=http_status not in {407, 451},
            terminal=http_status in {407, 451},
        )
    return ChallengeResult(final_url=final_url, http_status=http_status, engine=engine)
