from __future__ import annotations

from typing import Any

from app.core.time import utc_now


def build_dry_run_pr_payload(
        *,
        repo: str,
        branch: str,
        base: str,
        title: str,
        files: list[dict[str, Any]],
        body: str | None = None,
        metadata: dict[str, Any] | None = None,
        agent: str | None = None,
) -> dict[str, Any]:
    created_at = utc_now().isoformat()
    return {
        "action": "create_pr_dry_run",
        "repo": repo,
        "branch": branch,
        "base": base,
        "title": title,
        "body": body or "Dry-run PR generated by Agency runtime; do not merge. CI will emit /tmp/verdict.json",
        "patchJson": {
            "files": files,
        },
        "metadata": {
            "created": created_at,
            "agent": agent,
            **(metadata or {}),
        },
    }
